version: '2'
services:
    jhipstercassandrasampleapplication-app:
        image: jhipstercassandrasampleapplication
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_CASSANDRA_CONTACTPOINTS=jhipstercassandrasampleapplication-cassandra
            - JHIPSTER_SLEEP=30 # gives time for the Cassandra cluster to start and execute the migration scripts
        ports:
            - 8080:8080
    jhipstercassandrasampleapplication-cassandra:
        extends:
            file: cassandra-cluster.yml
            service: jhipstercassandrasampleapplication-cassandra
    jhipstercassandrasampleapplication-cassandra-node:
        image: cassandra:3.9
        environment:
            - CASSANDRA_SEEDS=jhipstercassandrasampleapplication-cassandra
    jhipstercassandrasampleapplication-cassandra-migration:
        extends:
            file: cassandra-migration.yml
            service: jhipstercassandrasampleapplication-cassandra-migration
        environment:
            - CREATE_KEYSPACE_SCRIPT=create-keyspace-prod.cql
